# Generated by Django 4.0.3 on 2022-04-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ramen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('rice', models.BooleanField(help_text='食べるならTrue', null=True)),
                ('amount', models.CharField(max_length=1)),
                ('date', models.DateTimeField(help_text='食事日')),
            ],
        ),
    ]
