# Generated by Django 3.2.5 on 2022-04-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RamenRecord',
            fields=[
                ('category', models.CharField(max_length=10)),
                ('rice', models.BooleanField(help_text='食べるならTrue', null=True)),
                ('amount', models.CharField(max_length=1)),
                ('date', models.DateTimeField(help_text='食事日')),
                ('calorie', models.AutoField(default=0, primary_key=True, serialize=False)),
            ],
        ),
    ]
